# Конфигурация Promtail — сбор логов и отправка в Loki (ДЗ тема 13)

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: app
    static_configs:
      - targets:
          - localhost
        labels:
          job: logs
          __path__: /var/log/app/*.log
    pipeline_stages:
      # Формат: [date time] [tenant] [severity] [module] [message]
      - regex:
          expression: '\[(?P<time>.*?)\] \[(?P<tenantid>.*?)\] \[(?P<severity>.*?)\] \[(?P<module>.*?)\] (?P<msg>.*)'
      - labels:
          tenantid:
          severity:
          module:
      - timestamp:
          format: "02.01.2006 15:04:05"
          source: time
          location: Europe/Moscow
      - labeldrop:
          - filename
          - time
      - output:
          source: msg
