# Конфигурация Prometheus — сбор метрик (ДЗ тема 13)

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Метрики самого Prometheus
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          instance: prometheus

  # Метрики Loki
  - job_name: loki
    static_configs:
      - targets: ["loki:3100"]
        labels:
          instance: loki

  # Метрики Promtail
  - job_name: promtail
    static_configs:
      - targets: ["promtail:9080"]
        labels:
          instance: promtail
