apiVersion: v1
kind: Secret
metadata:
  name: {{ include "credit-scoring.fullname" . }}-secrets
  labels:
    {{- include "credit-scoring.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.database.url | quote }}
